include("dataset.jl")

iris_y, iris_X = iris_dataset()
createImage(iris_X, "iris")
wine_y, wine_X = wine_dataset()
createImage(wine_X, "wine")
y_blobs, X_blobs_df = blobs()
createImage(X_blobs_df, "blobs")
y_moons, X_moons_df = moons()
createImage(X_moons_df, "moons")
y_circles, X_circles_df = circle()
createImage(X_circles_df, "circles")